trigger:
- main

pr:
- "*"

variables:
  - group: azure_env

jobs:
- job: buildAndDeploy
  displayName: 'Build & Deploy'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet build --configuration Release
    displayName: 'Build .NET Project'

  - script: |
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      docker-compose --version
    displayName: 'Install Docker Compose'

  - script: |
      docker-compose -f docker-compose.yml build
    displayName: 'Build Docker Image using Docker Compose'

  - script: |
      echo $(servicePrincipalKey) | az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId)
      
      az webapp config container set --name $(appServiceName) --resource-group $(resourceGroup) --docker-custom-image-name $(dockerHubUsername)/$(dockerImageName):latest
    displayName: 'Deploy Docker Container to Azure Web App'
