trigger:
- main

pr:
- "*"

variables:
  - group: azure_env

jobs:
- job: buildAndDeploy
  displayName: 'Build, Push & Deploy'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet build --configuration Release
    displayName: 'Build .NET Project'

  - script: |
      sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      docker-compose --version
    displayName: 'Install Docker Compose'

  - script: |
      docker-compose -f docker-compose.yml build
    displayName: 'Build Docker Image using Docker Compose'

  - script: |
      # Автентифікація через Service Principal
      export ARM_CLIENT_ID=$(servicePrincipalId)
      export ARM_CLIENT_SECRET=$(servicePrincipalKey)
      export ARM_SUBSCRIPTION_ID=$(subscriptionId)
      export ARM_TENANT_ID=$(tenantId)
      
      az login --service-principal --username $(servicePrincipalId) --password $(servicePrincipalKey) --tenant $(tenantId)
      
      az webapp config set --name $(appServiceName) --resource-group $(resourceGroup) --net-framework-version "7.0"
      az webapp up --name $(appServiceName) --resource-group $(resourceGroup) --sku F1
    displayName: 'Deploy to Azure App Service'
